name: fooderlich
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  flutter_slidable: ^2.0.0
  platform: ^3.1.0
  flutter_svg: ^1.1.4
  shared_preferences: ^2.0.15
  json_annotation: ^4.6.0
  chopper: ^6.1.4
  logging: ^1.0.2
  provider: ^6.0.3
  equatable: ^2.0.5
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11
  synchronized: ^3.0.0+3
  sqlbrite: ^2.3.0
  path: ^1.8.2
  dio: ^5.5.0+1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  chopper_generator: ^6.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/
